#!/usr/bin/env bash
# check-public-clean.sh — Detect private tooling artifacts and sensitive content.
#
# Scans tracked files for local-tooling artifacts, real credentials, private
# keys, seeds and runtime files that must not be shipped in a public release.
#
# Usage:
#   bash scripts/check-public-clean.sh
#
# Exit codes:
#   0 — clean (no issues found)
#   1 — issues found (review output before committing)

set -euo pipefail

ISSUES=0

flag() {
    echo "  [ISSUE] $1"
    ((ISSUES++)) || true
}

ok() {
    echo "  [OK]    $1"
}

header() {
    echo ""
    echo "--- $1 ---"
}

# Files to scan: tracked + staged (excludes .venv, node_modules, .git, logs)
SCAN_FILES=$(git ls-files 2>/dev/null | grep -Ev '\.(ndjson|lock)$' | grep -Ev '^(frontend/node_modules|\.venv|logs)' || true)

if [ -z "${SCAN_FILES}" ]; then
    echo "No tracked files found. Run inside a git repository."
    exit 0
fi

# ---------------------------------------------------------------------------
# 1. Local tooling artifacts
# ---------------------------------------------------------------------------
header "Local tooling artifacts"

TOOL_FILE_PATTERN="CL""AUDE\.md"
TOOL_GENERATED_PATTERN="Generated by Cl""aude"
CHAT_GENERATED_PATTERN="Generated by Ch""atGPT"
MARKER_PATTERN="A""I-generated"
LOCAL_MEMORY_PATTERN="memória ""operacional"
OLD_CHAT_PATTERN="con""versa antiga"
REASONING_PATTERN="raci""ocínio interno"

for pattern in "${TOOL_FILE_PATTERN}" "\.claude/" "${LOCAL_MEMORY_PATTERN}" "operacional para sessões" "${REASONING_PATTERN}" "${OLD_CHAT_PATTERN}"; do
    MATCHES=$(echo "${SCAN_FILES}" | xargs grep -l "${pattern}" 2>/dev/null || true)
    MATCHES=$(echo "${MATCHES}" | grep -Ev '^(\.gitignore|scripts/check-public-clean\.sh)$' || true)
    if [ -n "${MATCHES}" ]; then
        flag "Pattern '${pattern}' found in: ${MATCHES}"
    fi
done
ok "Local tooling scan complete"

# ---------------------------------------------------------------------------
# 2. Generated-content markers
# ---------------------------------------------------------------------------
header "Generated-content markers in public files"

for pattern in "${MARKER_PATTERN}" "${TOOL_GENERATED_PATTERN}" "${CHAT_GENERATED_PATTERN}" "Copilot generated"; do
    MATCHES=$(echo "${SCAN_FILES}" | xargs grep -il "${pattern}" 2>/dev/null || true)
    MATCHES=$(echo "${MATCHES}" | grep -Ev '^scripts/check-public-clean\.sh$' || true)
    if [ -n "${MATCHES}" ]; then
        flag "Pattern '${pattern}' found in: ${MATCHES}"
    fi
done
ok "Generated-content scan complete"

# ---------------------------------------------------------------------------
# 3. Hardcoded credentials (beyond example defaults)
# ---------------------------------------------------------------------------
header "Hardcoded credentials"

for pattern in "rpcpassword=[^n]" "BEGIN PRIVATE KEY" "BEGIN RSA PRIVATE KEY" "-----BEGIN EC" "xprv" "xpub" "zprvA" "zpub"; do
    MATCHES=$(echo "${SCAN_FILES}" | xargs grep -l "${pattern}" 2>/dev/null || true)
    MATCHES=$(echo "${MATCHES}" | grep -Ev '^scripts/check-public-clean\.sh$' || true)
    if [ -n "${MATCHES}" ]; then
        case "${MATCHES}" in
            *".env.example"* | *"bitcoin.conf.example"* | *"README"* | *"docs/"* | *"${TOOL_FILE_PATTERN}"*)
                : # expected in example/doc files
                ;;
            *)
                flag "Credential pattern '${pattern}' found in: ${MATCHES}"
                ;;
        esac
    fi
done
ok "Credential scan complete"

# ---------------------------------------------------------------------------
# 4. Files that must never be committed
# ---------------------------------------------------------------------------
header "Files that must not be in repo"

for dangerous in ".env" "CL""AUDE.md" ".claude/settings.local.json"; do
    if git ls-files --error-unmatch "${dangerous}" &>/dev/null 2>&1; then
        flag "File '${dangerous}' is tracked by git — it should be gitignored"
    fi
done
ok "Dangerous file check complete"

# ---------------------------------------------------------------------------
# 5. Runtime logs
# ---------------------------------------------------------------------------
header "Runtime NDJSON logs"
LOG_FILES=$(git ls-files logs/ 2>/dev/null | grep '\.ndjson$' || true)
if [ -n "${LOG_FILES}" ]; then
    flag "NDJSON log files are tracked: ${LOG_FILES}"
else
    ok "No NDJSON log files tracked"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=============================="
echo "  Public-clean check"
if [ "${ISSUES}" -eq 0 ]; then
    echo "  Result: CLEAN (0 issues)"
    echo "=============================="
    echo ""
    exit 0
else
    echo "  Result: ${ISSUES} issue(s) found"
    echo "=============================="
    echo ""
    echo "Review and fix the issues above before committing."
    exit 1
fi
